# Permalinks
permalink:           pretty

# Setup
exclude:             [CNAME, Gemfile, README.md, LICENSE.md, scratch.md]
unpublished:         true
show_drafts:         false
title:               masterspace
tagline:             
description:         'A blog by Jason Masters.'
url:                 http://masterspace.run
baseurl:             ''

# About/contact
author:
  name:              Jason Masters
  url:               masterspace.run
  email:             jason@masterspace.run

# Custom data
established:         2014
license:             CC BY 4.0
license_url:         http://creativecommons.org/licenses/by/4.0/legalcode
